### ISSUE TITLE
Add Default Club Data and Seed Clubs Collection

### ISSUE THREAD

**Issue by tycho01** [clubsearch-manoa/clubsearch-manoa#23]
Do all work for this task in a branch called issue-23

Adding default clubs to populate clubs collection with upon server startup.
Branch off of issue-21

**Comment by TristanYousufLeo** [comment]
Addendum: Default club data did not exist, added it in so Mongo.js can use the data to seed the Clubs collection on server startup

**Comment by tycho01** [comment]
Addendum: Default club data did not exist, added it to settings.development.json to seed Clubs collection with when server starts up in Mongo.js

**Comment by tycho01** [comment]
Update: Removed code in schema that caused unexpected behavior, added additional constraints to schema

**Comment by tycho01** [comment]
Update: Removed code in schema that caused unexpected behavior, added additional constraints to schema
