### ISSUE TITLE
Populate the database

### ISSUE THREAD

**Issue by TristanYousufLeo** [clubsearch-manoa/clubsearch-manoa#61]
Do all work for this task in a branch called issue-61

Branch off of test-m2
Take converted JSON file from issue-60 and import clubs into mongo database

**Comment by tycho01** [comment]
Removed redundant code fragment from Startup.jsx, fixed createUser function in Mongo.js. Imported JSON file containing real club data into Clubs Collection, adjusted Clubs schema constraints, fixed ESLint errors
